# Generated by Django 6.1 on 2026-08-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الجوال')),
                ('brand', models.CharField(max_length=100, verbose_name='الماركة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='phones/', verbose_name='صورة الجوال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
