# Generated by Django 6.1 on 2026-08-08 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'جوال', 'verbose_name_plural': 'الجوالات'},
        ),
        migrations.RemoveField(
            model_name='phone',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='description',
        ),
        migrations.AddField(
            model_name='phone',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='categories.category', verbose_name='التصنيف'),
        ),
    ]
