# Generated by Django 6.1 on 2026-08-21 07:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_options_remove_phone_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='warranty', serialize=False, to='phones.phone')),
                ('duration_months', models.IntegerField(default=12)),
                ('provider', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={},
        ),
        migrations.RemoveField(
            model_name='phone',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
        migrations.AddField(
            model_name='phone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='phones.category'),
        ),
        migrations.AddField(
            model_name='phone',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='phones', to='phones.feature'),
        ),
    ]
