# Generated by Django 6.1 on 2026-08-24 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_category_feature_warranty_alter_phone_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='created_at',
        ),
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='phones/', verbose_name='صورة الجوال'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='phones.category'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='features',
            field=models.ManyToManyField(blank=True, to='phones.feature'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
