# Generated by Django 5.2.17 on 2026-08-27 01:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def copy_legacy_categories(apps, schema_editor):
    legacy_category = apps.get_model("phones", "Category")
    legacy_phone = apps.get_model("phones", "Phone")
    category = apps.get_model("categories", "Category")
    for old_category in legacy_category.objects.all().order_by("pk"):
        target = category.objects.filter(pk=old_category.pk).first()
        if target is None:
            target = category.objects.filter(name=old_category.name).first()
        if target is None:
            target = category.objects.create(name=old_category.name, icon="bi-phone")
        legacy_phone.objects.filter(category_id=old_category.pk).update(category_id=target.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_alter_category_icon_and_more'),
        ('phones', '0004_remove_phone_created_at_phone_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('confirmed', 'مؤكد'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_name', models.CharField(max_length=150, verbose_name='اسم الجوال وقت الطلب')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
            ],
            options={
                'verbose_name': 'عنصر طلب',
                'verbose_name_plural': 'عناصر الطلب',
            },
        ),
        migrations.RunPython(copy_legacy_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='phone',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='categories.category', verbose_name='التصنيف'),
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['title'], 'verbose_name': 'ميزة', 'verbose_name_plural': 'المميزات'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'جوال', 'verbose_name_plural': 'الجوالات'},
        ),
        migrations.AlterModelOptions(
            name='warranty',
            options={'verbose_name': 'ضمان', 'verbose_name_plural': 'الضمانات'},
        ),
        migrations.AddField(
            model_name='phone',
            name='battery',
            field=models.CharField(blank=True, max_length=100, verbose_name='البطارية'),
        ),
        migrations.AddField(
            model_name='phone',
            name='brand',
            field=models.CharField(default='', max_length=100, verbose_name='الشركة'),
        ),
        migrations.AddField(
            model_name='phone',
            name='camera',
            field=models.CharField(blank=True, max_length=100, verbose_name='الكاميرا'),
        ),
        migrations.AddField(
            model_name='phone',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='اللون'),
        ),
        migrations.AddField(
            model_name='phone',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='phone',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='الموديل'),
        ),
        migrations.AddField(
            model_name='phone',
            name='operating_system',
            field=models.CharField(blank=True, max_length=80, verbose_name='نظام التشغيل'),
        ),
        migrations.AddField(
            model_name='phone',
            name='ram',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الرام GB'),
        ),
        migrations.AddField(
            model_name='phone',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حجم الشاشة بالبوصة'),
        ),
        migrations.AddField(
            model_name='phone',
            name='storage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='مساحة التخزين GB'),
        ),
        migrations.AddField(
            model_name='phone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم الميزة'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='phones', to='phones.feature', verbose_name='المميزات'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاح للبيع'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم الجوال'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='المخزون'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='duration_months',
            field=models.PositiveIntegerField(default=12, verbose_name='المدة بالشهور'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='phone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='warranty', serialize=False, to='phones.phone', verbose_name='الجوال'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='provider',
            field=models.CharField(max_length=100, verbose_name='مزود الضمان'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['brand', 'model'], name='phones_phon_brand_d43801_idx'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['category', 'is_available'], name='phones_phon_categor_d003a8_idx'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='phones.order', verbose_name='الطلب'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='phones.phone', verbose_name='الجوال'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
