# Generated by Django 5.2.17 on 2026-08-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'تصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi-phone', help_text='اسم أيقونة Bootstrap مثل bi-phone أو bi-apple', max_length=50, verbose_name='الأيقونة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف'),
        ),
    ]
